# Generated by Django 4.2.1 on 2023-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
