# Generated by Django 4.2.1 on 2023-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_seller_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
