# Generated by Django 4.2.1 on 2023-06-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seller_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
